### ISSUE TITLE
crash on seeing any item in this mod

### ISSUE THREAD

**Issue by TheNimbleNinja** [Yoghurt4C/LilTaterReloaded#11]
https://gist.github.com/TheNimbleNinja/ead7f3055102bcb371bb23508296446a

**Comment by Yoghurt4C** [comment]
how
@ 
how

**Comment by Yoghurt4C** [comment]
something's clearly forcing BuiltinItemRenderer to load before MinecraftClient is instantiated, so it's not my problem - but it won't crash my mod after https://github.com/Yoghurt4C/LilTaterReloaded/commit/5b09ebb2ffe7309e1d5d03786566c39c7d1e7e52
