### ISSUE TITLE
crash on opening loot chest

### ISSUE THREAD

**Issue by TheNimbleNinja** [Yoghurt4C/LilTaterReloaded#12]
https://gist.githubusercontent.com/natanfudge/ea95a46b8e070b3260376c4aca06829a/raw/275c3706cf5385b3f02de707f3158135a1591082/crash.txt

**Comment by Yoghurt4C** [comment]
try updating to the latest version

**Comment by Yoghurt4C** [comment]
any changes in behaviour?

**Comment by Yoghurt4C** [comment]
this shouldn't happen in 1.1.14, so I'm assuming it's closed due to lack of further input
