### ISSUE TITLE
[1.16-pre7] Client crash

### ISSUE THREAD

**Issue by kwpugh** [Yoghurt4C/LilTaterReloaded#3]
Log: https://gist.github.com/kwpugh/2fa0a0acd1631118ba5c25bcbabe85e5

**Comment by Yoghurt4C** [comment]
thank you github for not sending me an email

**Comment by Yoghurt4C** [comment]
fixed in https://github.com/Yoghurt4C/LilTaterReloaded/commit/9708f4b10f02a27b5d86421c9d35af8de47f0eff
