### ISSUE TITLE
my tater keeps showing up as a black and purple block.

### ISSUE THREAD

**Issue by potatoesandtaters** [Yoghurt4C/LilTaterReloaded#7]
![image](https://user-images.githubusercontent.com/79527021/108863752-71158e80-75e9-11eb-918f-fd0b2bc6924c.png)

It might be because I put them into the actual asset files but I'm not too sure.

**Comment by Yoghurt4C** [comment]
under what circumstances does this happen? is that your own, custom tater? do you have any mods that touch rendering (canvas/sodium/etc)?

**Comment by potatoesandtaters** [comment]
It's a custom tater, it happens whenever I rename it to the name of the tater and I have sodium. It could also be because I moved the tater one block up.
![image](https://user-images.githubusercontent.com/79527021/108864628-48da5f80-75ea-11eb-874b-e11f4021c561.png)
Side view.
![image](https://user-images.githubusercontent.com/79527021/108864714-60194d00-75ea-11eb-8c2d-ed6682dd505d.png)
Back view.
![image](https://user-images.githubusercontent.com/79527021/108864754-69a2b500-75ea-11eb-8ed8-270422606424.png)
Front view.
(he's pretty smexy, isn't he?)

**Comment by Yoghurt4C** [comment]
alright, so:
1. try this without sodium
2. if it still doesn't work, something may be off with your modelpath. make sure you put the json model *specifically* under `assets/yourmodid/models/tater/`, and there also should be errors in the console and latest.log every time you reload resources (just before you get to the main menu and when you change resourcepacks)

**Comment by potatoesandtaters** [comment]
I'll check it out, thanks! I'll edit this when I start it up without Sodium. To be honest though, I got a bit confused on the steps, so that could be a factor too. (I didn't know what it meant by "make a resource pack" so eventually I crammed it all into the assets of the mod itself using 7-zip oops)

Alright, edit, it looks like it's still not working, even without Sodium. I'll look into the 2nd thing now.

**Comment by Yoghurt4C** [comment]
you can "make" a resourcepack by creating a folder or zip file under .minecraft/resourcepacks and creating a text file called pack.mcmeta inside that folder with the following json object:
```json
{
  "pack": {
    "pack_format": 6,
    "description": "my cool resourcepack"
  }
}
```
minecraft will consider it to be a resourcepack and load it automatically. your method should also work just fine, even if it's a hackjob

**Comment by potatoesandtaters** [comment]
Ah, well I did this and uh, I got pretty lost hahaha (I struggle at reading and understanding a bit so it's a bit complicated for my brain)

**Comment by potatoesandtaters** [comment]
Found it.
[15:27:50] [Worker-Main-12/WARN]: Unable to load model: 'ltr:models/tater/creeper_tater#' referenced from: ltr:models/tater/creeper_tater#: com.google.gson.JsonParseException: assets/creeper tater is not valid resource location
[15:27:50] [Worker-Main-12/WARN]: Unable to load model: 'ltr:tater/creeper_tater' referenced from: ltr:models/tater/creeper_tater#: com.google.gson.JsonParseException: assets/creeper tater is not valid resource location
I think it is the modelpath.

**Comment by Yoghurt4C** [comment]
do you have a space in the filename?

**Comment by potatoesandtaters** [comment]
I'll check now.

**Comment by potatoesandtaters** [comment]
![image](https://user-images.githubusercontent.com/79527021/108866927-95bf3580-75ec-11eb-9de1-a25d7d5cc7f9.png)
![image](https://user-images.githubusercontent.com/79527021/108866972-a1126100-75ec-11eb-8575-732775edfbe9.png)
![image](https://user-images.githubusercontent.com/79527021/108867015-abccf600-75ec-11eb-9336-27f2e13bebf3.png)
![image](https://user-images.githubusercontent.com/79527021/108867152-cef7a580-75ec-11eb-8a1e-a8c6cee60813.png)

**Comment by Yoghurt4C** [comment]
uh, please try removing the creeper_tater line from powertaters/liltaterreloaded/ltr.json and see if it still errors out

**Comment by Yoghurt4C** [comment]
also, can you check if the texture references inside your model json refer to `assets/creeper tater`?

**Comment by potatoesandtaters** [comment]
I'll check both.
Result: 
[15:39:43] [Worker-Main-9/WARN]: Unable to load model: 'ltr:models/tater/creeper_tater#' referenced from: ltr:models/tater/creeper_tater#: com.google.gson.JsonParseException: assets/creeper tater is not valid resource location
[15:39:43] [Worker-Main-9/WARN]: Unable to load model: 'ltr:tater/creeper_tater' referenced from: ltr:models/tater/creeper_tater#: com.google.gson.JsonParseException: assets/creeper tater is not valid resource location


Might've found the problem here.
![image](https://user-images.githubusercontent.com/79527021/108868265-f00cc600-75ed-11eb-8be0-36153d54b4fa.png)
**There's a space.**

OH, I know where that space came from. I mistakenly put my file as "creeper tater" originally, but changed it. I forgot about the texture in the file, oops.

**Comment by Yoghurt4C** [comment]
you must put the texture under `assets/ltr/textures` and reference it with `ltr:creeper_tater`. in case you care about subfolders, just look at the [existing model jsons inside the mod](https://github.com/Yoghurt4C/LilTaterReloaded/blob/fabric-1.16/src/main/resources/assets/ltr/models/tater/tofu_survivor.json#L3)

**Comment by potatoesandtaters** [comment]
Alright, thank you. Sorry if it's a stupid issue, I'm just a bit dumb LOL.

**Comment by Yoghurt4C** [comment]
it's alright. all of us get brought down by mojang's nondescriptive errors and ass formats

**Comment by potatoesandtaters** [comment]
Hahaha and their weird confusing code in general sometimes

**Comment by potatoesandtaters** [comment]
Would this work?
![image](https://user-images.githubusercontent.com/79527021/108869716-5ba36300-75ef-11eb-882e-67b1f0a3dd8d.png)

**Comment by Yoghurt4C** [comment]
of course not, that's not a valid identifier. just copypaste the string above that to the particle definition (ie `"particle": "ltr:tater/creeper_tater"`) and, assuming your texture is in assets/ltr/textures/tater/creeper_tater.png, it should work without further input

**Comment by potatoesandtaters** [comment]
Ah alright, thank you.

**Comment by potatoesandtaters** [comment]
Hey, it worked! Thank you a lot. I'll remember this for next time.
My little bean child.
![image](https://user-images.githubusercontent.com/79527021/108871105-b6898a00-75f0-11eb-8d8e-80d2b736c793.png)
